 export const cardData=[
    {
        id:1,
        img:"https://orchasp.com/wp-content/uploads/2023/02/ET.png",
        path:"https://economictimes.indiatimes.com/industry/transportation/railways/orchasp-gets-order-from-centre-for-railway-information/articleshow/97575145.cms"
    },
    {
        id:2,
        img:"https://orchasp.com/wp-content/uploads/2023/02/TOI.jpg",
        path:"https://timesofindia.indiatimes.com/india/orchasp-limited-bags-order-from-centre-for-railway-information-cris/articleshow/97577693.cms"
    },
    {
        id:3,
        img:"https://orchasp.com/wp-content/uploads/2023/02/Zee-Business.jpg",
        path:"https://www.zeebiz.com/companies/news-orchasp-limited-bags-order-from-centre-for-railway-information-220609"
    },
    {
        id:4,
        img:"https://orchasp.com/wp-content/uploads/2023/02/MSN-2.png",
        path:"https://www.msn.com/en-in/money/news/orchasp-limited-bags-order-from-centre-for-railway-information/ar-AA176uXc"
    },
    {
        id:5,
        img:"https://orchasp.com/wp-content/uploads/2023/02/BS.png",
        path:"https://www.business-standard.com/content/press-releases-ani/orchasp-limited-bags-order-from-centre-for-railway-information-cris-123020600841_1.html"
    },
    {
        id:6,
        img:"https://orchasp.com/wp-content/uploads/2023/02/TST.jpg",
        path:"https://www.torontosuntimes.com/news/orchasp-limited-bags-order-from-centre-for-railway-information-cris20230206145806/"
    }

]